spring:
  application:    name: employee-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:    username: root
    password: mypass
    url: jdbc:mysql://localhost:3306/employee
    driver-class-name: com.mysql.cj.jdbc.Driver
server:  port: 9000
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka